akkadotnet/Hyperion

Hyperion.Tests/ImmutableCollectionsTests.cs, Hyperion/Hyperion.project.lock.json, Hyperion/SerializerFactories/ImmutableCollectionsSerializerFactory.cs
This PR contains a two fixes for bugs, that haven't been observed by tests observed so far:
- Using immutable collections inside class referenced through interfaces (old version was blowing up, because it tried to find `ImmutableCollection.CreateRange` constructor method based on interface).
- Uncommented test for ImmutableStack - old version was deserializing stack with elements applied in reversed order.
/cc https://github.com/akkadotnet/akka.net/pull/2421 (this PR should fix the problem)
=> Fix for immutable interface calls and immutable stacks

RELEASE_NOTES.md
Includes bug fixes for immutable data structures and lists.
See the full set of changes here: [Hyperion 0.9.2 Milestone](https://github.com/akkadotnet/Hyperion/milestone/2)
=> Hyperion v0.9.2 release notes

README.md
A simple link to the Wire in the README.md - a name change got some people confused, as they didn't know what to expect from Hyperion.
Also included current status in order to set expectations about API and binary format straight.
=> Added information about Hyperion/Wire relationship.

Hyperion/Extensions/TypeEx.cs, Hyperion/ValueSerializers/ObjectSerializer.cs, Hyperion/ValueSerializers/TypeSerializer.cs
The serializer appears to be built to use short names of types, but the code wasn't implemented this way yet.
This patch makes the serializer write the type name as `FullName, Assembly` instead of `FullName, Assembly, Version=..., PublicKey=...`. This fixes issues where deserializer finds a different version of the assembly on the other side.
The reason for this patch is that I'm currently having problems using DistributedPubSub, because Akka.NET depends on a slightly older version of System.Collections.Immutable than some other libraries. As serialized objects carry assembly qualified names, a node with different version of a library throw exceptions trying to decode messages exchanged by the mediator as it cannot find the exact version of the assembly the message was serialized with.
=> Use short assembly name during serialization to avoid versioning problems

Hyperion/Extensions/TypeEx.cs, Hyperion/ValueSerializers/ObjectSerializer.cs, Hyperion/ValueSerializers/TypeSerializer.cs
Reverts akkadotnet/Hyperion#28.  During the process of targeting .NET Standard 1.6, we found that the signature being used for `Type.GetType` in this PR isn't available in netstandard1.6.   We made an attempt to use compiler directives to enable this feature for net45 compilation only, but there is the potential for inconsistent wire format across netstandard1.6 and net45 versions of the assembly if we do that.  Plan is to get .NET Core up and running and then come back to making this feature compatible with netstandard1.6.
=> Revert "Use short assembly name during serialization to avoid versioning problems"

Hyperion.Tests.Performance/Hyperion.Tests.Performance.csproj, Hyperion.sln, build.ps1, build.sh
Upgraded .NET Core tooling to newest stable release 1.0.0.  Also upgraded Hyperion.Tests.Performance due to eventual breaking change with NBench 1.0.0 targeting .NET 4.5.2 instead of 4.5.
=> Upgrade dotnet cli to 1.0.0 and Hyperion.Tests.Performance to .NET 4.5.2

Hyperion.Tests/ISerializableTests.cs, Hyperion/Hyperion.csproj
Fixed: https://github.com/akkadotnet/Hyperion/issues/42
And have added unit tests
=> Restored support of ISerialization

Hyperion.Tests/CollectionTests.cs, Hyperion/SerializerOptions.cs
This exception is fired when `ValueSerializerFactory` is registered for some (not direct) descendant of `ICollection`.
Take a look at [this line](https://github.com/akkadotnet/Hyperion/blob/3133431d04281546c71402775fc951540a9cbf7d/Hyperion/SerializerFactories/EnumerableSerializerFactory.cs#L83) - it can't decide which `Add` to use.
Stumbled when tried to serialize Json.Net's `JArray` (don't ask why ¯\\_(ツ)_/¯ ) which is derived from `JCollection` which is derived from `ICollection` and others.
Fix is to place specific `ValueSerializerFactory` at begining in the `Options` prop. I think [this](https://github.com/akkadotnet/Hyperion/blob/dev/Hyperion/SerializerOptions.cs#L35) proofs my assumptions.
=> AmbiguousMatchException fix

build.fsx, build.ps1
Add `nugetprerelease=dev` flag and version suffix set to `-beta-123` when publishing nightlies to MyGet feed.
=> Nugetprerelease flag for nightly build naming

RELEASE_NOTES.md, build.fsx
Updates release notes for v0.9.5 production release.
Also makes the prerelease numbering `v0.9.5-1-beta` instead of `v0.9.5-beta-1` to account for MyGet feed ordering bug
=> Update release notes for v0.9.5

build.fsx
Fix nuget publish when symbols aren't required to nuget push
=> Fix nuget publish when symbols aren't required to nuget push

build.fsx
* add option for not publishing symbols for production release
* bad folder name
=> Fix nuget publish when symbols aren't required to nuget push (#69)

Hyperion.Tests/ExpressionTests.cs, Hyperion/Extensions/TypeEx.cs, Hyperion/SerializerFactories/MethodInfoSerializerFactory.cs
Attempts to fix #77  by supporting serialization of closed constructed generic methodinfos. 
Makes use of a more relaxed GetMethod implementation (defined in `TypeEx`) that will match closed constructed methods to generic method definitions in a sensible way.
FYI, I don't have FSharp on this machine so have not checked that those tests still work.
=> Support generic methods in methodinfoserializerfactory

Hyperion.PerfTest/Program.cs, Hyperion.PerfTest/Tests/DateTimeOffsetTest.cs, Hyperion.Tests/PrimitivesTests.cs, Hyperion/Extensions/TypeEx.cs, Hyperion/NoAllocBitConverter.cs, Hyperion/Serializer.cs, Hyperion/ValueSerializers/DateTimeOffsetSerializer.cs, README.md
Handles DateTimeOffset as a primitive, the same way as DateTime is currently handled. It serializes the offset in minutes, instead of DateTimeKind. The offset can be +/- 720 minutes, so a signed short has been used.
=> Added support for DateTimeOffset as a primitive

README.md, RELEASE_NOTES.md, src/common.props
**Maintenance release for Hyperion v0.9.***
This patch mostly contains bugfixes and enhancements to the existing Hyperion v0.9.* branch. No major API changes have been made.
* [EnumerableSerializeFactory fixes](https://github.com/akkadotnet/Hyperion/pull/81)
* [Fix: ObjectDisposedException cannot be deserialized](https://github.com/akkadotnet/Hyperion/issues/64)
* [Added support for DateTimeOffset as a primitive](https://github.com/akkadotnet/Hyperion/pull/79)
You can [see the full set of changes for Hyperion v0.9.7 here](https://github.com/akkadotnet/Hyperion/milestone/5).
=> Hyperion v0.9.7 release notes [dev]

RELEASE_NOTES.md, src/common.props
**Maintenance release for Hyperion v0.9.***
This small patch conists of the following bug fixes to Hyperion v0.9.* branch:
* [Support for FSharpSet<T>](https://github.com/akkadotnet/Hyperion/pull/92)
=> V0.9.8 release notes

RELEASE_NOTES.md, src/Hyperion.Tests/FSharpTests.cs, src/Hyperion/SerializerFactories/EnumerableSerializerFactory.cs, src/common.props
**Maintenance release for Hyperion v0.9.***
This small patch conists of the following bug fixes to Hyperion v0.9.* branch:
* [Support for FSharpSet<T>](https://github.com/akkadotnet/Hyperion/pull/92)
=> v0.9.8 production release

src/Hyperion.Tests/Bugs.cs, src/Hyperion/SerializerSession.cs
fixes #96 
not sure if the `TypedEqualityComparer` can be improved
=> preserve reference is checking type to prevent InvalidCastException

build.fsx, src/common.props
If TeamCity isn't available to pass in a build number environment variable, beta NuGet packages will now be named using the following convention:
```
[PackageName].[VerisonInReleaseNotes]-beta[DateTime.UtcNow.Ticks]
```
If the `BUILD_NUMBER` environment variable is available, NuGet packages will be built the same way they are now:
```
[PackageName].[VerisonInReleaseNotes]-beta[BUILD_NUMBER]
```
=> made it easier to generate beta packages of Hyperion locally

build-system/README.md, build-system/azure-pipeline.template.yaml, build-system/linux-pr-validation.yaml, build-system/nightly-builds.yaml, build-system/windows-pr-validation.yaml, build-system/windows-release.yaml, build.fsx, build.ps1, build.sh, src/Hyperion/Hyperion.csproj, src/common.props
- Bumped hyperion core to net452
- Updated build scripts to latest version. This included nbench targets although its not used in the solution. Did this so we end up with the same scripts all around. Makes it easier to maintain since there is no need for different build descriptions for each repo.
- Note that signing targets are also in there, but they are disabled in the target itself
=> Build system update

build-system/pr-validation.yaml, build.ps1
Building on @Danthar's work - added a file that runs both Linux and Windows PR validation in parallel.
=> added X-plat PR validation

RELEASE_NOTES.md, src/common.props
Hyperion now [supports cross-framework communication between .NET Core and .NET Framework](https://github.com/akkadotnet/Hyperion/pull/116).
=> added v0.9.10 Release Notes

src/Hyperion/Hyperion.csproj
need to do this in order to release a patch that will allow us to run Hyperion in .NET Core 3.0 on Akka.NET v1.3.*
=> moved Hyperion back to .NET 4.5

RELEASE_NOTES.md, src/common.props
[Hyperion now targets .NET 4.5 again so it can be included inside Akka.NET v1.3.* releases](https://github.com/akkadotnet/Hyperion/pull/141).
=> added v0.9.11 release notes

RELEASE_NOTES.md, src/Hyperion.Benchmarks/Hyperion.Benchmarks.csproj, src/Hyperion/Hyperion.csproj, src/common.props
[Hyperion now targets .NET 4.5 again so it can be included inside Akka.NET v1.3.* releases](https://github.com/akkadotnet/Hyperion/pull/141).
=> v0.9.11 Release

src/Hyperion.Tests/Bugs.cs, src/Hyperion.Tests/Hyperion.Tests.csproj, src/Hyperion/Extensions/TypeEx.cs, src/Hyperion/Hyperion.csproj, src/Hyperion/ValueSerializers/TypeSerializer.cs
Close #144 
The basic idea is to ignore assembly version, if it is specified in incoming message type's manifest.
=> Fix version tolerance when bad assembly version specified in type manifest

src/Hyperion.Tests/CrossFrameworkSerializationTests.cs
Making it easier to see which combination of platforms resulted in a failure
=> rewrote CrossFrameworkSerializationTests as xUnit theory

RELEASE_NOTES.md, src/common.props
* Added version tolerance during deserialization.
* Added `ArrayList` and non-generic `IEnumerable` support.
=> added v0.9.2 release notes

src/Hyperion.Tests/GenericDictionarySerializerTests.cs, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs
=> IDictionary<TKey, TValue> support

src/Hyperion.Tests/GenericDictionarySerializerTests.cs, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs
Close #157
Some fun with reflection, and now it works without requiring `IDictionary` to be implemented.
=> Update IDictionary<T, V> serializer to not use IDictionary assumption

RELEASE_NOTES.md, src/common.props
* [Added support for serializing and deserializing `IDictionary<TKey, TValue>`](https://github.com/akkadotnet/Hyperion/pull/156)
=> added v0.9.13 release notes

src/Hyperion.Tests/GenericDictionarySerializerTests.cs, src/Hyperion/Hyperion.csproj, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs
`DictionarySerializerFactory.BuildSerializer()` does not play nicely with classes that uses private or protected default constructor. Modified the `Activator.CreateInstance()` call so that it tries to instantiate using a non-public constructor first, then tries to use the public constructor if the first attempt throws.
=> Fix DictionarySerializerFactory to work with private or protected default constructor

README.md, RELEASE_NOTES.md, src/Hyperion.Tests/GenericDictionarySerializerTests.cs, src/Hyperion.Tests/Hyperion.Tests.csproj, src/Hyperion/Hyperion.csproj, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs
* [Added support for serializing and deserializing `IDictionary<TKey, TValue>` with private and protected default constructor] (https://github.com/akkadotnet/Hyperion/pull/162)
=> v0.9.14 Release

src/Hyperion.Tests/GenericDictionarySerializerTests.cs, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs
`Type.GetGenericTypeDefinition()` in Dictionary serialization throws if the `Type.GetInterfaces()` of the class returns a non-generic interface before an `IDictionary` interface.
=> Fix Type.GetGenericTypeDefinition() interface error

RELEASE_NOTES.md, src/common.props
* [Fix `Type.GetGenericTypeDefinition()` interface error](https://github.com/akkadotnet/Hyperion/pull/166)
=> added v0.9.15 release notes

RELEASE_NOTES.md, src/Hyperion.Tests/GenericDictionarySerializerTests.cs, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs, src/common.props
* [Fix `Type.GetGenericTypeDefinition()` interface error](https://github.com/akkadotnet/Hyperion/pull/166)
=> v0.9.15 Release

src/Hyperion.Tests/ImmutableCollectionsTests.cs, src/Hyperion/SerializerFactories/DictionarySerializerFactory.cs
Added a special case handler for ReadOnlyDictionary because DictionarySerializerFactory could not generate deserializer for ReadOnlyDictionary because ReadOnlyDictionary does not have a parameterless constructor.
=> Add deserialization support for ReadOnlyDictionary

src/Hyperion.Tests/Hyperion.Tests.csproj, src/common.props
Currently, Azure Pipelines PR Validations will always fail because the msbuild compiler for netcoreapp2.1 target framework is acting strange, it is requiring arbitarily specific SDK version, depending on which msbuild is installed.
We're dropping netcoreapp2.1 build target for the test project.
=> Fix unit test problem

Hyperion.sln, src/Hyperion.API.Tests/CoreAPISpec.cs, src/Hyperion.API.Tests/CoreApiSpec.ApproveApi.approved.txt, src/Hyperion.API.Tests/Hyperion.API.Tests.csproj, src/Hyperion.Akka.Integration.Tests/Hyperion.Akka.Integration.Tests.csproj, src/Hyperion.Akka.Integration.Tests/IntegrationSpec.cs, src/Hyperion.Tests/CrossFrameworkSerializationTests.cs, src/Hyperion.Tests/Hyperion.Tests.csproj, src/Hyperion/SerializerOptions.cs, src/common.props
=> Fix settings constructor backward compatibility issue

src/Hyperion.Tests/CollectionTests.cs, src/Hyperion/SerializerFactories/ArraySerializerFactory.cs
Closes #232
Was moved from #233
Clean up PR, remove all unnescessary codes.
=> Fix user defined struct array serialization failure

src/Hyperion.Tests/Bugs.cs, src/Hyperion/Extensions/ReflectionEx.cs
This PR fixes https://github.com/akkadotnet/akka.net/issues/5102.
The error is caused by differences in order of letters and special characters on different platforms.
This blog posts has more details of such differences and suggests using StringComparer.Ordinal.
=> Order type fields by oridnal to keep the same order on multiple platforms

src/Hyperion.Benchmarks/Hyperion.Benchmarks.csproj, src/common.props
Now targets: `net461`, `netcoreapp3.1`, and `net5.0`
=> updated benchmarks to run on modern .NET platforms

src/Hyperion.Benchmarks/Program.cs, src/Hyperion.Benchmarks/SerializeStructsBenchmark.cs
Hyperion.Benchmarks.SerializeStructsBenchmark did not initialize the `Serializer` field during `Init()` properly, it is null and NRE crashes the benchmark.
=> Fix SerializeStructBenchmark, Serializer not initialized

src/Hyperion/Internal/Annotations.cs
Embed the type name in the exception message so that the offending type can be inspected in logs instead of having to inspect the exception instance itself
=> Improve EvilDeserializationException message

src/Hyperion/Extensions/TypeEx.cs, src/Hyperion/Serializer.cs
Part of  #303
Move static `TypeEx.TypeNameLookup` into a field of `Serializer` instead
=> Convert byte array key to type cache from static to instance bound
